/* ================================================================================================
 * File: builtin.h
 * Brief: Declarations for the embedded images under src/ps2/builtin/ (generated by
 *        src/tools/imgdump.c from the original game assets). These are always available,
 *        no filesystem needed: the console font/background, HUD tiles and the palette.
 *        NOTE: Shared header between C and C++.
 *
 * This source code is released under the GNU GPL v2 license.
 * ================================================================================================ */

#ifndef PS2_BUILTIN_H
#define PS2_BUILTIN_H

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/* 256-entry RGBA palette (0xAABBGGRR), from the game's colormap.pcx. Expands
 * 8-bit palettized images and backs the color index taken by DrawFill. */
extern const unsigned int global_palette[256];

/* conchars.pcx: 8x8-pixel console glyphs in a 16x16 grid.
 * RGBA-32; transparent texels have alpha 0. */
extern const int conchars_width;
extern const int conchars_height;
extern const unsigned char conchars_data[];

/* conback.pcx: console background artwork. RGB-16 (5-5-5-1). */
extern const int conback_width;
extern const int conback_height;
extern const unsigned char conback_data[];

/* backtile.pcx: tileable background used by DrawTileClear. RGB-16 (5-5-5-1). */
extern const int backtile_width;
extern const int backtile_height;
extern const unsigned char backtile_data[];

/* inventory.pcx: inventory screen frame. RGB-16 (5-5-5-1). */
extern const int inventory_width;
extern const int inventory_height;
extern const unsigned char inventory_data[];

/* help.pcx: help/computer screen frame. RGB-16 (5-5-5-1). */
extern const int help_width;
extern const int help_height;
extern const unsigned char help_data[];

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif // PS2_BUILTIN_H
